config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]

  root 'departments#index'
  resources :users
  resources :departments, shallow: true do
    resources :wokers, except: [:index]
  end


  namespace 'api', format: 'json' do
    namespace 'v1' do
      resources :users
      resources :departments, shallow: true do
        resources :wokers, except: [:index]
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable
  validates :email, presence: true, uniqueness: true

end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :authorize_admin
      before_action :set_user, only: [:show, :update, :destroy]

      # GET /users
      def index
        @users = User.all
        render json: @users
      end

      # GET /users/1
      def show
        render json: @user
      end

      # POST /users
      def create
        @user = User.new(user_params)

        if @user.save
          render json: @user, status: :created, location: @user
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /users/1
      def update
        if @user.update(user_params)
          render json: @user
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      end

      # DELETE /users/1
      def destroy
        if current_user == @user
          head :no_content
        else
          @user.destroy
          head :no_content
        end
      end


      private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
          @user = User.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def user_params
          params.except(:format, :user).permit(:email, :password, :admin)
        end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show

  end


  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, flash: { notice: "User #{@user.email} was successfully created." }
    else
      redirect_to users_path
    end
  end

  # GET /users/edit/1
  def edit

  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, flash: { notice: "User #{@user.email} was successfully updated!" }
    else
      redirect_to users_path
    end
  end

  # DELETE /users/1
  def destroy
    if current_user == @user
      redirect_to users_path, notice: "You can't destroy yourself."
    else
      @user.destroy
      redirect_to users_path, flash: { notice: "User #{@user.email} was successfully deleted!" }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.fetch(:user, {}).permit(:email, :password, :admin)
    end
end

app/views/users/_form.html.slim
= form_for @user, html:{class: "form-horizontal"} do |f|
  .form-group
    = f.label :email, class:'col-sm-1 control-label'
    .col-sm-3
      = f.text_field :email, class: "form-control"
    = f.error_span(:email)
  .form-group
    = f.label :password, class:'col-sm-1 control-label'
    .col-sm-3
      = f.text_field :password, class: "form-control"
    = f.error_span(:password)
  .form-group
    = f.label :role, class:'col-sm-1 control-label'
    .col-sm-3
      = f.select :admin, options_for_select([['user', 'false'], ['admin', 'true']]), class: "form-control"
    = f.error_span(:admin)
  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit nil, class: "btn btn-info"
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
.main-block
  .head
    .button
      = link_to 'Add user', new_user_path, :class => 'btn btn-primary'
  table.table.table-striped
    thead
      tr
        th= model_class.human_attribute_name(:id)
        th[width="50%"]= model_class.human_attribute_name(:email)
        th= model_class.human_attribute_name(:admin)
        th[width="25%"]=t '.actions', :default => t("helpers.actions")
    tbody
      - @users.each do |user|
        tr
          td= link_to user.id, user_path(user)
          td= user.email
          td= user.admin
          td
            = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

  table.table.table-bordered
    tr
      td [width="30%", align="right"]
        |Email:
      td
        = @user.email
    tr
      td [align="right"]
        |Admin:
      td
        = @user.admin
    tr
      td [align="right"]
        |Current sign in at:
      td
        = @user.current_sign_in_at
    tr
      td [align="right"]
        |Current sign in IP:
      td
        = @user.current_sign_in_ip
    tr
      td [align="right"]
        |Last sign in at:
      td
        = @user.last_sign_in_at
    tr
      td [align="right"]
        |Last sign in IP:
      td
        = @user.last_sign_in_ip

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'