config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]

  root 'departments#index'
  resources :users
  resources :departments, shallow: true do
    resources :wokers, except: [:index]
  end


  namespace 'api', format: 'json' do
    namespace 'v1' do
      resources :users
      resources :departments, shallow: true do
        resources :wokers, except: [:index]
      end
    end
  end

end

app/models/department.rb
class Department < ApplicationRecord
  has_many :wokers, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/api/v1/departments_controller.rb
module Api
  module V1
    class DepartmentsController < ApplicationController
      before_action :set_department, only: [:show, :update, :destroy]

      # GET /departments
      def index
        if params[:sort]
          @departments = Department.order(params[:sort]).all.page(params[:page]).per(10)
        else
          @departments = Department.all.page(params[:page]).per(10)
        end
        render json: @departments
      end

      # GET /departments/1
      def show
        if params[:sort]
          @wokers = Woker.order(params[:sort]).where(department_id: @department.id).page(params[:page]).per(20)
        else
          @wokers = Woker.where(department_id: @department.id).page(params[:page]).per(20)
        end
        render json: @wokers
      end


      # POST /departments
      def create
        @department = Department.new(department_params)

        if @department.save
          render json: @department, status: :created, location: @department
        else
          render json: @department.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /departments/1
      def update
        if @department.update(department_params)
          render json: @department
        else
          render json: @department.errors, status: :unprocessable_entity
        end
      end

      # DELETE /departments/1
      def destroy
        @department.destroy
        head :no_content
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_department
          @department = Department.find(params[:id])
        end

        # Only allow a trusted parameter "white list" through.
        def department_params
          params.except(:format, :department).permit(:title, :description)
        end

    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  def index
    if params[:sort]
      @departments = Department.order(params[:sort]).all.page(params[:page]).per(10)
    else
      @departments = Department.all.page(params[:page]).per(10)
    end
  end

  # GET /departments/1
  def show
    if params[:sort]
      @wokers = Woker.order(params[:sort]).where(department_id: @department.id).page(params[:page]).per(20)
    else
      @wokers = Woker.where(department_id: @department.id).page(params[:page]).per(20)
    end
  end


  # GET /departments/new
  def new
    @department = Department.new
  end

  # POST /departments
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path, flash: { notice: "Department added!" }
    else
      redirect_to departments_path, flash: { notice: "Department not added!" }
    end
  end

  # GET /departments/edit/1
  def edit

  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      redirect_to departments_path, flash: { notice: "Department updated!" }
    else
      redirect_to departments_path, flash: { notice: "Department not updated!" }
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    redirect_to departments_path, flash: { notice: "Department deleted!" }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def department_params
      params.fetch(:department, {}).permit(:title, :description)
    end

end

app/views/departments/_form.html.slim
= form_for @department, html:{class: "form-horizontal"} do |f|
  .form-group
    = f.label :title, class:'col-sm-1 control-label'
    .col-sm-4
      = f.text_field :title, class: "form-control"
    = f.error_span(:title)
  .form-group
    = f.label :description, class:'col-sm-1 control-label'
    .col-sm-4
      = f.text_field :description, class: "form-control"
    = f.error_span(:description)
  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit nil, class: "btn btn-info"
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), departments_path, :class => 'btn'

app/views/departments/edit.html.slim
- model_class = Department
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/departments/index.html.slim
- model_class = Department
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
.main-block
  .head
    .sorting
      = form_tag departments_path, method: :get, class: 'sort' do
        .form-group
          = check_box_tag('sort', 'title', params[:sort], onchange: 'this.form.submit()')
          = label :sort, 'Sort by title'

    .button
      = link_to 'New department', new_department_path, :class => 'btn btn-primary'

  table.table.table-striped

    thead
      tr
        th= model_class.human_attribute_name(:id)
        th= model_class.human_attribute_name(:title)
        th= model_class.human_attribute_name(:description)
        th=t '.actions', :default => t("helpers.actions")
    tbody
      - @departments.each do |department|
        tr
          td= department.id
          td= link_to department.title, department_path(department)
          td= department.description
          td
            = link_to t('.show', :default => t("helpers.links.show")), department_path(department), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_department_path(department), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), department_path(department), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

  .pg
    = paginate @departments

.chart-block
  = column_chart Woker.group(:department_id).count

app/views/departments/new.html.slim
- model_class = Department
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/departments/show.html.slim
- model_class = Department
.page-header
  h1 = @department.title
  h4 = @department.description

.main-block
  .head
    .sorting
      = form_tag department_path, method: :get, class: 'sort' do
        .form-group
          = label :sort, 'Sort by:'
          = select_tag('sort', options_for_select([['Name', 'name'], ['Surname', 'surname'], ['Born', 'born'], ['Gender', 'gender']], params[:sort]), onchange: 'this.form.submit()')
        = submit_tag 'submit'
        = javascript_tag "$('.sort input').hide()"
    .button
      = link_to 'Add woker', new_department_woker_path(@department), :class => 'btn btn-primary'

  table.table.table-striped
    thead
      tr
        th= model_class.human_attribute_name(:id)
        th= model_class.human_attribute_name(:name)
        th= model_class.human_attribute_name(:surname)
        th= model_class.human_attribute_name(:position)
        th= model_class.human_attribute_name(:born)
        th= model_class.human_attribute_name(:gender)
        th=t '.actions', :default => t("helpers.actions")
    tbody
      - @wokers.each do |woker|
        tr
          td= woker.id
          td= woker.name
          td= woker.surname
          td= woker.position
          td= woker.born
          td= woker.gender
          td
            = link_to t('.show', :default => t("helpers.links.show")), woker_path(woker), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_woker_path(woker), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), woker_path(woker), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

  .pg
    = paginate @wokers